title = 'Pochven'
description = "Pochven—學習與紀錄之旅程的起點"
author = "DennisMa"
baseURL = "https://pochven.netlify.app/"
languageCode = 'zh-tw'

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  authorName = "Dennis Ma"
  toc = true

  [params.taxonomyNames]
    categories = "分類"
    tags = "TAG"